#!/usr/bin/env php
<?php

use Kicaj\Bench\CliBench;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPBENCH_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

/** @noinspection PhpIncludeInspection */
require PHPBENCH_COMPOSER_INSTALL;

try {
    CliBench::make($argv)->run();
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
